site_name: I-analyzer Readers
repo_url: https://github.com/CentreForDigitalHumanities/ianalyzer-readers
plugins:
  - mkdocstrings
nav:
  - 'index.md'
  - 'usage.md'
  - Examples:
    - 'example_csv.md'
    - 'example_xml.md'
    - 'example_custom.md'
    - 'combining_readers.md'
  - 'api.md'
watch:
  - docs
  - ianalyzer_readers
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 3